const questions = [{
    question: " UNIVAC is",
    a: "Universal Automatic Computer",
    b: "Universal Array Computer",
    c: "Unique Automatic Computer",
    d: "Unvalued Automatic Computer",ans: "c",
},
{
    question: " The basic operations performed by a computer are",
    a: "Arithmetic operation",
    b: "Logical operation",
    c: "Storage and relative",
    d: "All the above",
},
{
    question: " The two major types of computer chips are",
    a: "External memory chip",
    b: "Primary memory chip",
    c: "Microprocessor chip",
    d: "Both b and c",
},
{
    question: " Microprocessors as switching devices are for which generation computers",
    a: "First Generation",
    b: "Second Generation",
    c: "Third Generation",
    d: "Fourth Generation",
},
{
    question: " What is the main difference between a mainframe and a super computer?",
    a: "Super computer is much larger than mainframe computers",
    b: "Super computers are much smaller than mainframe computers",
    c: "Supercomputers are focused to execute few programs as fast as possible while mainframe uses its power to execute as many programs concurrently",
    d: "Supercomputers are focused to execute as many programs as possible while mainframe uses its power to execute few programs as fast as possible",
},
{
    question: " ASCII and EBCDIC are the popular character coding systems",
    a: "Extended Binary Coded Decimal Interchange Code",
    b: "Extended Bit Code Decimal Interchange Code",
    c: "Extended Bit Case Decimal Interchange Code",
    d: "Extended Binary Case Decimal Interchange Code",
},
{
    question: " The brain of any computer system is",
    a: "ALU",
    b: "Memory",
    c: "CPU",
    d: "Control unit",
},
{
    question: " Storage capacity of magnetic disk depends on",
    a: "tracks per inch of surface",
    b: "bits per inch of tracks",
    c: "disk pack in disk surface",
    d: "All of above",
},
{
    question: " The two kinds of main memory are:",
    a: "Primary and secondary",
    b: "Random and sequential",
    c: "ROM and RAM",
    d: "All of above",
},
{
    question: " A storage area used to store data to a compensate for the difference in speed at which the different units can handle data is",
    a: "Memory",
    b: "Buffer",
    c: "Accumulator",
    d: "Address",
},
{
    question: " Computer is free from tiresome and boardoom",
    a: "Accuracy",
    b: "Reliability",
    c: "Diligence",
    d: "Versatility",
},
{
    question: " Integrated Circuits (Ics) are related to which generation of computers?",
    a: "First generation",
    b: "Second generation",
    c: "Third generation",
    d: "Fourth generation",
},
{
    question: " CD-ROM is a",
    a: "Semiconductor memory",
    b: "Memory register",
    c: "Magnetic memory",
    d: "None of above",
},
{
    question: " A hybrid computer",
    a: "Resembles digital computer",
    b: "Resembles analogue computer",
    c: "Resembles both a digital and analogue computer",
    d: "None of the above",
},
{
    question: " Which type of computers uses the 8-bit code called EBCDIC?",
    a: "Minicomputers",
    b: "Microcomputers",
    c: "Mainframe computers",
    d: "Super computer",
},
{
    question: " The ALU of a computer responds to the commands coming from",
    a: "Primary memory",
    b: "Control section",
    c: "External memory",
    d: "Cache memory",
},
{
    question: " Chief component of first generation computer was",
    a: "Transistors",
    b: "Vacuum Tubes and Valves",
    c: "Integrated Circuits",
    d: "None of above",
},
{
    question: " To produce high quality graphics (hardcopy) in color, you would want to use a/n",
    a: "RGB monitor",
    b: "Plotter",
    c: "Ink-jet printer",
    d: "Laser printer",
},
{
    question: " What are the stages in the compilation process?",
    a: "Feasibility study, system design and testing",
    b: "Implementation and documentation",
    c: "Lexical Analysis, syntax analysis, and code generation",
    d: "None of the above",
},
{
    question: " Which of the following IC was used in third generation of computers?",
    a: "SSI",
    b: "MSI",
    c: "LSI",
    d: "Both a and b",
},
{
    question: " The main electronic component used in first generation computers was",
    a: "Transistors",
    b: "Vacuum Tubes and Valves",
    c: "Integrated Circuits",
    d: "None of above",
},
{
    question: " A dumb terminal has",
    a: "an embedded microprocessor",
    b: "extensive memory",
    c: "independent processing capability",
    d: "a keyboard and screen",
},
{
    question: " One millisecond is",
    a: "1 second",
    b: "10thof a seconds",
    c: "1000th of a seconds",
    d: "10000th of a seconds",
},
{
    question: " The output quality of a printer is measured by",
    a: "Dot per sq inch",
    b: "Dot per inch",
    c: "Dots printed per unit time",
    d: "All of the above",
},
{
    question: " Which of the following was a special purpose computer?",
    a: "ABC",
    b: "ENIAC",
    c: "EDVAC",
    d: "All of the above",
},
{
    question: " What was the computer invented by Attanasoff and Clifford?",
    a: "Mark I",
    b: "ABC",
    c: "Z3",
    d: "None of above",
},
{
    question: " Which of the following storage devices can store maximum amount of data?",
    a: "Floppy Disk",
    b: "Hard Disk",
    c: "Compact Disk",
    d: "Magneto Optic Disk",
},
{
    question: " Which computer was considered the first electronic computer until 1973 when court invalidated the patent?",
    a: "ENIAC",
    b: "MARK I",
    c: "Z3",
    d: "ABC",
},
{
    question: " A physical connection between the microprocessor memory and other parts of the microcomputer is known as",
    a: "Path",
    b: "Address bus",
    c: "Route",
    d: "All of the above",
},
{
    question: " High density double sided floppy disks could store _____ of data",
    a: "40 MB",
    b: "44 GB",
    c: "40 GB",
    d: "44 MB",
},
{
    question: " A high quality CAD system uses the following for printing drawing and graphs",
    a: "Dot matrix printer",
    b: "Digital plotter",
    c: "Line printer",
    d: "All of the above",
},
{
    question: " Which of the following is not an input device?",
    a: "OCR",
    b: "Optical scanners",
    c: "Voice recognition device",
    d: "COM (Computer Output to Microfilm)",
},
{
    question: " The accuracy of the floating-point numbers representable in two 16-bit words of a computer is approximately",
    a: "16 digits",
    b: "6 digits",
    c: "9 digits",
    d: "All of above",
},
{
    question: " In most of the IBM PCs, the CPU, the device drivers, memory, expansion slots and active components are mounted on a single board",
    a: "Motherboard",
    b: "Daughterboard",
    c: "Bredboard",
    d: "Fatherboard",
},
{
    question: " In most IBM PCs, the CPU, the device drives, memory expansion slots and active components are mounted on a single board",
    a: "Motherboard",
    b: "Breadboard",
    c: "Daughter board",
    d: "Grandmother board",
},
{
    question: " Magnetic disks are the most popular medium for",
    a: "Direct access",
    b: "Sequential access",
    c: "Both of above",
    d: "None of above",
},
{
    question: " A technique used by codes to convert an analog signal into a digital bit stream is known as",
    a: "Pulse code modulation",
    b: "Pulse stretcher",
    c: "Query processing",
    d: "Queue management",
},
{
    question: " Regarding a VDU, Which statement is more correct?",
    a: "It is an output device",
    b: "It is an input device",
    c: "It is a peripheral device",
    d: "It is hardware item",
},
{
    question: " A modern electronic computer is a machine that is meant for",
    a: "Doing quick mathematical calculations",
    b: "Input, storage, manipulation and outputting of data",
    c: "Electronic data processing",
    d: "Performing repetitive tasks accurately",
},
{
    question: " When was vacuum tube invented?",
    a: "1900",
    b: "1960",
    c: "1910",
    d: "1880",
},
{
    question: " Which of the following produces the best quality graphics reproduction?",
    a: "Laser printer",
    b: "Ink jet printer",
    c: "Plotter",
    d: "Dot matrix printer",
},
{
    question: " Computers with 80286 microprocessor is",
    a: "XT computer",
    b: "AT comptuers",
    c: "PS/2 computer",
    d: "None of above",
},
{
    question: " An application suitable for sequential processing is",
    a: "Processing of grades",
    b: "Payroll processing",
    c: "Both a and b",
    d: "All of above",
},
{
    question: " Which of the following is not processing?",
    a: "arranging",
    b: "manipulating",
    c: "calculating",
    d: "gathering",
},
{
    question: " The digital computer was developed primarily in",
    a: "USSR",
    b: "Japan",
    c: "USA",
    d: "UK",
},
{
    question: " Software in computer",
    a: "Enhances the capabilities of the hardware machine",
    b: "Increase the speed of central processing unit",
    c: "Both of above",
    d: "None of above",
},
{
    question: " Today’s computer giant IBM was earlier known by different name which was changes in 1924",
    a: "Tabulator Machine Co<br>",
    b: "Computing Tabulating Recording Co<br>",
    c: "The Tabulator Ltd<br>",
    d: "International Computer Ltd",
},
{
    question: " Before a disk drive can access any sector record, a computer program has to provide the record’s disk address",
    a: "Track number",
    b: "Sector number",
    c: "Surface number",
    d: "All of above",
},
{
    question: " The arranging of data in a logical sequence is called",
    a: "Sorting",
    b: "Classifying",
    c: "Reproducing",
    d: "Summarizing",
},
{
    question: " What is the responsibility of the logical unit in the CPU of a computer?",
    a: "To produce result",
    b: "To compare numbers",
    c: "To control flow of information",
    d: "To do math’s works",
},
{
    question: " Abacus was the first",
    a: "electronic computer",
    b: "mechanical computer",
    c: "electronic calculator",
    d: "mechanical calculator",
},
{
    question: " If in a computer, 16 bits are used to specify address in a RAM, the number of addresses will be",
    a: "216",
    b: "65,536",
    c: "64K",
    d: "Any of the above",
},
{
    question: " Instructions and memory address are represented by",
    a: "Character code",
    b: "Binary codes",
    c: "Binary word",
    d: "Parity bit",
},
{
    question: " The terminal device that functions as a cash register, computer terminal, and OCR reader is the:",
    a: "Data collection terminal",
    b: "OCR register terminal",
    c: "Video Display terminal",
    d: "POS terminal",
},
{
    question: " A set of flip flops integrated together is called ____",
    a: "Counter",
    b: "Adder",
    c: "Register",
    d: "None of the above",
},
{
    question: " People often call ______ as the brain of computer system",
    a: "Control Unit",
    b: "Arithmetic Logic Unit",
    c: "Central Processing Unit",
    d: "Storage Unit",
},
{
    question: " Which is used for manufacturing chips?",
    a: "Bus",
    b: "Control unit",
    c: "Semiconductors",
    d: "A and b only",
},
{
    question: " The value of each bead in heaven is",
    a: "1",
    b: "3",
    c: "5",
    d: "7",
},
{
    question: " The first computer introduced in Nepal was",
    a: "IBM 1400",
    b: "IBM 1401",
    c: "IBM 1402",
    d: "IBM1402",
},
{
    question: " Mnemonic a memory trick is used in which of the following language?",
    a: "Machine language",
    b: "Assembly language",
    c: "High level language",
    d: "None of above",
},
{
    question: " Instruction in computer languages consists of",
    a: "OPCODE",
    b: "OPERAND",
    c: "Both of above",
    d: "None of above",
},
{
    question: " Which generation of computer is still under development",
    a: "Fourth Generation",
    b: "Fifth Generation",
    c: "Sixth Generation",
    d: "Seventh Generation",
},
{
    question: " A register organized to allow to move left or right operations is called a ____",
    a: "Counter",
    b: "Loader",
    c: "Adder",
    d: "Shift register",
},
{
    question: " Which was the most popular first generation computer?",
    a: "IBM 1650",
    b: "IBM 360",
    c: "IBM 1130",
    d: "IBM 2700",
},
{
    question: " Which is considered a direct entry input device?",
    a: "Optical scanner",
    b: "Mouse and digitizer",
    c: "Light pen",
    d: "All of the above",
},
{
    question: " A set of information that defines the status of resources allocated to a process is",
    a: "Process control",
    b: "ALU",
    c: "Register Unit",
    d: "Process description",
},
{
    question: " Each set of Napier’s bones consisted of ______ rods",
    a: "5",
    b: "9",
    c: "11",
    d: "13",
},
{
    question: " BCD is",
    a: "Binary Coded Decimal",
    b: "Bit Coded Decimal",
    c: "Binary Coded Digit",
    d: "Bit Coded Digit",
},
{
    question: " When was the world’s first laptop computer introduced in the market and by whom?",
    a: "Hewlett-Packard, 1980",
    b: "Epson, 1981",
    c: "Laplink Traveling Software Inc, 1982",
    d: "Tandy Model-200, 1985",
},
{
    question: " From which generation operating systems were developed?",
    a: "First",
    b: "Second",
    c: "Third",
    d: "Fourth",
},
{
    question: " The first firm to mass-market a microcomputer as a personal computer was",
    a: "IBM",
    b: "Super UNIVAC",
    c: "Radio Shaks",
    d: "Data General Corporation",
},
{
    question: " How many address lines are needed to address each machine location in a 2048 x 4 memory chip?",
    a: "10",
    b: "11",
    c: "8",
    d: "12",
},
{
    question: " Properly arranged data is called",
    a: "Field",
    b: "Words",
    c: "Information",
    d: "File",
},
{
    question: " A computer consists of",
    a: "A central processing unit",
    b: "A memory",
    c: "Input and output unit",
    d: "All of the above",
},
{
    question: " Why are vacuum tubes also called valves?",
    a: "Because they can amplify the weak signals and make them strong",
    b: "Because they can stop or allow the flow of current",
    c: "Both of above",
    d: "None of above",
},
{
    question: " John Napier invented Logarithm in",
    a: "1614",
    b: "1617",
    c: "1620",
    d: "None of above",
},
{
    question: " An integrated circuit is",
    a: "A complicated circuit",
    b: "An integrating device",
    c: "Much costlier than a single transistor",
    d: "Fabricated on a tiny silicon chip",
},
{
    question: " What type of control pins are needed in a microprocessor to regulate traffic on the bus, in order to prevent two devices from trying to use it at the same time?",
    a: "Bus control",
    b: "Interrupts",
    c: "Bus arbitration",
    d: "Status",
},
{
    question: " Where as a computer mouse moves over the table surface, the trackball is",
    a: "Stationary",
    b: "Difficult to move",
    c: "Dragged",
    d: "Moved in small steps",
},
{
    question: " Which of the following is used as a primary storage device?",
    a: "Magnetic drum",
    b: "Hard Disks",
    c: "Floppy",
    d: "All of above",
},
{
    question: " Multi user systems provided cost savings for small business because they use a single processing unit to link several",
    a: "Personal computers",
    b: "Workstations",
    c: "Dumb terminals",
    d: "Mainframes",
},
{
    question: " What are the three decisions making operations performed by the ALU of a computer?",
    a: "Grater than",
    b: "Less than",
    c: "Equal to",
    d: "All of the above",
},
{
    question: " The word processing task associated with changing the appearance of a document is",
    a: "Editing",
    b: "Writing",
    c: "Formatting",
    d: "All of above",
},
{
    question: " Nepal brought a computer for census of 2028 BS",
    a: "first generation",
    b: "second generation",
    c: "third generation",
    d: "fourth generation",
},
{
    question: " Algorithm and Flow chart help us to",
    a: "Know the memory capacity",
    b: "Identify the base of a number system",
    c: "Direct the output to a printer",
    d: "Specify the problem completely and clearly",
},
{
    question: " Which statement is valid about computer program?",
    a: "It is understood by a computer",
    b: "It is understood by programmer",
    c: "It is understood user",
    d: "Both a &amp; b",
},
{
    question: " The difference between memory and storage is that memory is _____ and storage is __",
    a: "Temporary, permanent",
    b: "Permanent, temporary",
    c: "Slow, fast",
    d: "All of above",
},
{
    question: " When was Pascaline invented?",
    a: "1617",
    b: "1620",
    c: "1642",
    d: "1837",
},
{
    question: " Which of the following statement is valid?",
    a: "Lady Augusta is the first programmer",
    b: "Ada is the daughter of Lord Byron, a famous English poet",
    c: "ADA is a programming language developed by US Defense",
    d: "All of above",
},
{
    question: " A compiler is a translating program which",
    a: "Translates instruction of a high level language into machine language",
    b: "Translates entire source program into machine language program",
    c: "It is not involved in program’s execution",
    d: "All of above",
},
{
    question: " What is required when more than one person uses a central computer at the same time?",
    a: "Light pen",
    b: "Mouse",
    c: "Digitizer",
    d: "Terminal",
},
{
    question: " Which of the following is the first computer to use Stored Program Concept?",
    a: "UNIVAC",
    b: "ENIAC",
    c: "EDSAC",
    d: "None of above",
},
{
    question: " The term gigabyte refers to",
    a: "1024 bytes",
    b: "1024 kilobytes",
    c: "1024 megabytes",
    d: "1024 gigabyte",
},
{
    question: " in which year was UK’s premier computing event called ?The which computer? started?",
    a: "",
    b: "",
    c: "",
    d: "",
},
{
    question: " Once you load the suitable program and provide required data, computer does not need human intervention",
    a: "Accuracy",
    b: "Reliability",
    c: "Versatility",
    d: "Automatic",
},
{
    question: " What is a brand?",
    a: "The name of companies that made computers",
    b: "The name of product a company gives to identify its product in market",
    c: "A name of class to indicate all similar products from different companies",
    d: "All of above",
},
{
    question: " Machine language is",
    a: "Machine dependent",
    b: "Difficult to program",
    c: "Error prone",
    d: "All of above",
},
{
    question: " A byte consists of",
    a: "One bit",
    b: "Four bits",
    c: "Eight bits",
    d: "Sixteen bits",
},
{
    question: " Modern Computers are very reliable but they are not",
    a: "Fast",
    b: "Powerful",
    c: "Infallible",
    d: "Cheap",
},
{question: "100. What is the date when Babbage conceived Analytical engine",
a: "1642",
b: "1837",
c: "1880",
d: "1850",}

];

const answers = ["A", "D", "D", "D", "C", "A", "C", "D", "C", "B", "C", "C", "D", "C", "C", "B", "B", "B", "C", "D", "B", "D", "C", "A", "A", "B", "B", "A", "B", "D", "B", "D", "B", "A", "A", "C", "A", "C", "B", "B", "C", "B", "C", "D", "C", "A", "B", "D", "A", "B", "D", "B", "B", "D", "C", "C", "C", "C", "B", "B", "C", "B", "D", "A", "D", "D"]
